resolver: lts-8.2

flags: {}

extra-package-dbs: []

packages:
- '.'
- core
- update
- infra
- db

- location:
    git: https://github.com/serokell/acid-state.git
    commit: 95fce1dbada62020a0b2d6aa2dd7e88eadd7214b
  extra-dep: true
- location:
    git: https://github.com/serokell/kademlia.git
    commit: bf65ac0cd50d2ccd7ef6507f0d71786c4bd10ae1
  extra-dep: true
- location:
    git: https://github.com/input-output-hk/plutus-prototype
    commit: 4e3f6a268c3b13af78516f78ac71cd6215f5b0bf
  extra-dep: true
- location:
    git: https://github.com/serokell/rocksdb-haskell.git
    commit: 4dfd8d61263d78a91168e86e8005eb9b7069389e
  extra-dep: true
- location:
    git: https://github.com/thoughtpolice/hs-ed25519
    # We're waiting on next release
    commit: 57adb970e198a9b377769ab46e776ec29f19cff6
  extra-dep: true
- location:
    git: https://github.com/input-output-hk/cardano-report-server.git
    commit: ede7a1a9eafd88e3449b38c7425f5529d6584014
  extra-dep: true
- location:
    git: https://github.com/serokell/time-warp-nt.git
    commit: b976bbafe0b0c7805f0a3b14ddd78f409ae30122
  extra-dep: true
# These two are needed for time-warp-nt
- location:
    git: https://github.com/avieth/network-transport-tcp
    commit: 1739cc6d5c73257201e5551088f4ba56d5ede15c
  extra-dep: true
- location:
    git: https://github.com/avieth/network-transport
    commit: f2321a103f53f51d36c99383132e3ffa3ef1c401
  extra-dep: true
- location:
    git: https://github.com/serokell/hslogger
    commit: cf5c742a07ef12e8eb2506775c77f22befa23d8f
  extra-dep: true
# todo replace it with hackage version
#- location:
#    git: https://github.com/serokell/serokell-util/
#    commit: 9f5e818ef9e9f07434b6c2ca51d2db8ae56309db
#  extra-dep: true

nix:
  shell-file: shell.nix

extra-deps:
- universum-0.2.1
- time-units-1.0.0
- UtilityTM-0.0.4
- serokell-util-0.1.4.0
- pvss-0.1
- base58-bytestring-0.1.0
- log-warper-0.5.1
- concurrent-extra-0.7.0.10       # not yet in lts-8
- derive-2.5.26                   # not yet in lts-8
- haskell-src-exts-1.17.1         # derive has not moved to 1.18 yet
- wreq-0.5.0.0                    # not yet in lts-8
- purescript-bridge-0.8.0.1

# This is for CI to pass --fast to all dependencies
apply-ghc-options: everything
